export const GET_COOKIE_FAILURE = 'GET_COOKIE_FAILURE';
export const GET_COOKIE_SUCCESS = 'GET_COOKIE_SUCCESS';

export const SET_TOUR_STEP = 'SET_TOUR_STEP';

export const SET_ESTIMATE_COUNTER = 'SET_ESTIMATE_COUNTER';

export const SET_TEAMSPACE_ID = 'SET_TEAMSPACE_ID';
