const types = {
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
  USER_LOGIN_AUTH_ERROR: 'USER_LOGIN_AUTH_ERROR',
  LICENSE_UPDATED: 'LICENSE_UPDATED',
  REFRESH_USER: 'REFRESH_USER',
  USER_TYPE: 'USER_TYPE',
  RESET_LAYOUT: 'RESET_LAYOUT',
  USER_LOGOUT: 'USER_LOGOUT',
}

export default types
